// Do not edit this file; automatically generated by build.py.
"use strict";


// Copyright 2012 Google Inc.  Apache License 2.0

Blockly.Blocks.procedures_defnoreturn=[],Blockly.Blocks.procedures_defreturn=[],Blockly.Blocks.procedures_mutatorcontainer=[],Blockly.Blocks.procedures_mutatorarg=[],Blockly.Blocks.procedures_ifreturn=[],Blockly.Blocks.controls_whileUntil=[],Blockly.Blocks.controls_doWhile=[],Blockly.Blocks.controls_repeat=[],Blockly.Blocks.controls_for=[],Blockly.Blocks.controls_flow_statements=[],Blockly.Blocks.controls_if=[],Blockly.Blocks.controls_if_if=[],Blockly.Blocks.controls_if_elseif=[],Blockly.Blocks.controls_if_else=[],Blockly.Blocks.logic_compare=[],Blockly.Blocks.logic_operation=[],Blockly.Blocks.logic_negate=[],Blockly.Blocks.logic_boolean=[],Blockly.Blocks.math_number=[],Blockly.Blocks.math_arithmetic=[],Blockly.Blocks.math_single=[],Blockly.Blocks.math_modulo=[],Blockly.Blocks.variables_get=[],Blockly.Blocks.variables_set=[],Blockly.Blocks.text=[],Blockly.Blocks.character={},Blockly.Blocks.text_join=[],Blockly.Blocks.text_create_join_container=[],Blockly.Blocks.text_create_join_item=[],Blockly.Blocks.text_append=[],Blockly.Blocks.text_length=[];